import { describe, it, expect } from "vitest";
import { Effect } from "effect";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import {
  prep,
  perfectReplace,
  replacePartWithMissingLeadingWhitespace,
  tryDotdotdots,
  SequenceMatcher,
  replaceClosestEditDistance,
  replaceMostSimilarChunk,
  parseDiffBlocks,
  applyDiffs,
} from "./AiderPatcher";
import { TreeSitterParserLive } from "./TreeSitterParser";

describe("AiderPatcher - Text Matching Waterfall Tests", () => {
  it("should prep strings cleanly", () => {
    const [c, lines] = prep("const x = 1;\nconst y = 2;\n");
    expect(c).toBe("const x = 1;\nconst y = 2;\n");
    expect(lines).toEqual(["const x = 1;\n", "const y = 2;\n"]);
  });

  it("should match exact sequences flawlessly using perfectReplace", () => {
    const wholeLines = ["const a = 1;\n", "const b = 2;\n", "const c = 3;\n"];
    const partLines = ["const b = 2;\n"];
    const replaceLines = ["const b = 99;\n"];

    const result = perfectReplace(wholeLines, partLines, replaceLines);
    expect(result).toBe("const a = 1;\nconst b = 99;\nconst c = 3;\n");
  });

  it("should handle relative indentation shifts accurately", () => {
    const wholeLines = ["  class Test {\n", "    run() {\n", "    }\n", "  }\n"];
    const partLines = ["run() {\n", "}\n"];
    const replaceLines = ["run() {\n", "  console.log(1);\n", "}\n"];

    const result = replacePartWithMissingLeadingWhitespace(wholeLines, partLines, replaceLines);
    expect(result).toBe("  class Test {\n    run() {\n      console.log(1);\n    }\n  }\n");
  });

  it("should skip blank leading lines generated by sloppy models", () => {
    const whole = "const x = 1;\nconst y = 2;\n";
    const part = "\nconst y = 2;\n";
    const replace = "const y = 99;\n";

    const [result, strategy] = replaceMostSimilarChunk(whole, part, replace);
    expect(result).toBe("const x = 1;\nconst y = 99;\n");
    expect(strategy).toBe("Skipped leading blank line match");
  });

  it("should support block matching utilizing line elisions (tryDotdotdots)", () => {
    const whole = "function compute() {\n  let x = 1;\n  // extra comments\n  let y = 2;\n  return x + y;\n}\n";
    const part = "function compute() {\n  let x = 1;\n  ...\n  return x + y;\n}\n";
    const replace = "function compute() {\n  let x = 100;\n  ...\n  return x + y;\n}\n";

    const result = tryDotdotdots(whole, part, replace);
    expect(result).toBe("function compute() {\n  let x = 100;\n  // extra comments\n  let y = 2;\n  return x + y;\n}\n");
  });

  it("should compute accurate similarity ratios via SequenceMatcher", () => {
    const matcher1 = new SequenceMatcher("abcd", "bcde");
    expect(matcher1.ratio()).toBe(0.75);

    const matcher2 = new SequenceMatcher("diet", "tide");
    expect(matcher2.ratio()).toBe(0.5);
  });

  it("should fall back gracefully to fuzzy sequence matching above threshold", () => {
    const wholeLines = ["const first = 1;\n", "const middlePoint = 2;\n", "const last = 3;\n"];
    const part = "const muddlePoint = 2;\n";
    const partLines = ["const muddlePoint = 2;\n"];
    const replaceLines = ["const middlePoint = 99;\n"];

    const result = replaceClosestEditDistance(wholeLines, part, partLines, replaceLines);
    expect(result).toBe("const first = 1;\nconst middlePoint = 99;\nconst last = 3;\n");
  });

  it("should cleanly parse SEARCH/REPLACE diff blocks", () => {
    const rawDiff = "\n<<<<<<< SEARCH\nconst a = 1;\n=======\nconst a = 99;\n>>>>>>> REPLACE\n";
    const blocks = parseDiffBlocks(rawDiff);
    expect(blocks.length).toBe(1);
    expect(blocks[0]).toEqual(["const a = 1;", "const a = 99;"]);
  });

  it("should transactionally apply and write files to disk via applyDiffs effect", async () => {
    const tempFile = path.join(process.cwd(), `aider-temp-${crypto.randomUUID()}.txt`);
    await fs.writeFile(tempFile, "initial content\nline 2\n", "utf-8");

    const patchJson = JSON.stringify({
      summary: "Apply test update",
      files: [
        {
          file_path: tempFile,
          code_diff: "\n<<<<<<< SEARCH\nline 2\n=======\nupdated line 2\n>>>>>>> REPLACE\n"
        }
      ]
    });

    const runner = applyDiffs(patchJson).pipe(Effect.provide(TreeSitterParserLive));
    const success = await Effect.runPromise(runner);
    expect(success).toBe(true);

    const updatedContent = await fs.readFile(tempFile, "utf-8");
    expect(updatedContent).toBe("initial content\nupdated line 2\n");

    await fs.unlink(tempFile);
  });

  it("should capture high-fidelity mismatch diagnostics when search block fails to match", async () => {
    const tempFile = path.join(process.cwd(), `aider-temp-diag-${crypto.randomUUID()}.txt`);
    await fs.writeFile(
      tempFile,
      "const a = 1;\nconst b = 2;\nconst c = 3;\nconst d = 4;\nconst e = 5;\n",
      "utf-8"
    );

    const patchJson = JSON.stringify({
      summary: "Apply mismatched update",
      files: [
        {
          file_path: tempFile,
          code_diff: "\n<<<<<<< SEARCH\nconst x = 999;\nconst y = 888;\nconst z = 777;\n=======\nconst abc = 123;\n>>>>>>> REPLACE\n"
        }
      ]
    });

    const runner = applyDiffs(patchJson).pipe(Effect.provide(TreeSitterParserLive));

    try {
      await Effect.runPromise(runner);
      throw new Error("Expected to fail");
    } catch (error: any) {
      expect(error._tag).toBe("PatchApplicationError");
      expect(error.failedSearchBlock).toContain("const x = 999;");
      expect(error.proposedReplacement).toContain("const abc = 123;");
      expect(error.actualContextSnippet).toContain("const b = 2;");
      expect(error.actualContextSnippet).toContain("const a = 1;");
      expect(error.actualContextSnippet).toContain("const c = 3;");
    }

    await fs.unlink(tempFile);
  });

    it("should successfully apply a Tier 3 AST-Node replacement when search block has malformed indentation/comments", async () => {
    const tempFile = path.join(process.cwd(), `aider-temp-ast-${crypto.randomUUID()}.ts`);
    const initialContent = [
      "export function calcPrice(price: number): number {",
      "  // original comment here",
      "  const tax = price * 0.1;",
      "  return price + tax;",
      "}"
    ].join("\n");

    await fs.writeFile(tempFile, initialContent, "utf-8");

    const patchJson = JSON.stringify({
      summary: "Apply AST replacement",
      files: [
        {
          file_path: tempFile,
          code_diff: [
            "\n<<<<<<< SEARCH",
            "export function calcPrice(price: number): number {",
            "         // completely broken comments and spacing",
            "  const tax = price * 99999;",
            "}",
            "=======",
            "export function calcPrice(price: number): number {",
            "  const tax = price * 0.15;",
            "  return price + tax;",
            "}",
            ">>>>>>> REPLACE\n"
          ].join("\n")
        }
      ]
    });

    const runner = applyDiffs(patchJson).pipe(Effect.provide(TreeSitterParserLive));
    const success = await Effect.runPromise(runner);
    expect(success).toBe(true);

    const updatedContent = await fs.readFile(tempFile, "utf-8");
    expect(updatedContent).toContain("const tax = price * 0.15;");

    await fs.unlink(tempFile);
  });

    it("should reject Tier 3 AST replacement if it generates syntax error nodes", async () => {
    const tempFile = path.join(process.cwd(), `aider-temp-ast-err-${crypto.randomUUID()}.ts`);
    const initialContent = [
      "export function calcPrice(price: number): number {",
      "  const tax = price * 0.1;",
      "  return price + tax;",
      "}"
    ].join("\n");

    await fs.writeFile(tempFile, initialContent, "utf-8");

    const patchJson = JSON.stringify({
      summary: "Apply broken AST replacement",
      files: [
        {
          file_path: tempFile,
          code_diff: [
            "\n<<<<<<< SEARCH",
            "export function calcPrice(price: number): number {",
            "  const tax = price * 99999;",
            "}",
            "=======",
            "export function calcPrice(price: number): number {",
            "  const tax = price * 0.15;",
            "  return price + tax;",
            "// unclosed brace here",
            ">>>>>>> REPLACE\n"
          ].join("\n")
        }
      ]
    });

    const runner = applyDiffs(patchJson).pipe(Effect.provide(TreeSitterParserLive));
    try {
      await Effect.runPromise(runner);
      throw new Error("Expected to fail");
    } catch (error: any) {
      expect(error._tag).toBe("PatchApplicationError");
    }

    await fs.unlink(tempFile);
  });
});
